Generify noc vhd
LaNoC-UFC/Phoenix pull request #25
Opened 2016-10-17 20:55 UTC by rafaelgmota

Turning NoC.vhd independence of NoC size

2016-10-17 22:17 UTC, rmilfont commented
@jmarcelof which function should we use? NUMBER_TO_ADDRESS or GET_ADDR? I´ve pushed the GET_ADDR, but it seems that NUMBER_TO_ADDRESS already exists and do the same.

2016-10-18 00:47 UTC, rafaelgmota commented
@rmilfont there is some differences between those two functions. NUMBER_TO_ADDRESS return 16 bits but just use the last 8 to represents x and y (4 bits for each one). The GET_ADDR function return 16 bits, using the first 8 to represent x and last 8 to represent y, making possible to have a larger NoC.

The desired is to use GET_ADDR, but at this point will need to make some others changes. Maybe this could be done at some other future issue.

2016-10-18 01:56 UTC, rmilfont commented
@rafaelgmota Fair enough.

2016-10-18 09:12 UTC, jmarcelof commented
I created #26 to address that issue.

2016-10-18 09:27 UTC, jmferreiratech requested changes

2016-10-18 09:27 UTC, jmarcelof commented on NoC/NOC.vhd
> +    credit_iLocal : in  regNrot);
Put the close parentheses on the next line.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/NOC.vhd
> +        fillLocalFlits: for i in 0 to NROT-1 generate
This line indentation doesn't seem ok.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/NOC.vhd
> +        generic map
When there's only one item, you can keep a map on a single line.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/NOC.vhd
> +        (
The open parentheses should be on the line above.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/Phoenix_package.vhd
> +    subtype pointer is std_logic_vector((TAM_POINTER-1) downto 0);
Remove the trailing spaces.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/Phoenix_package.vhd
> +
Remove this blank line.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/Phoenix_package.vhd
> +    type arrayNrot_regNport is array((NROT-1) downto 0) of regNport; -- a -- array (NROT)(NPORT)
Remove the comment.

2016-10-18 09:27 UTC, jmarcelof commented on NoC/NOC.vhd
> +            clock_rx(i)(0)              <= clock_tx(i+NUM_Y)(1);
Could you try to replace these hard-coded values by constants (0 by EAST, 1 by WEST...)? The old version of modelsim seemed to not accept this kind of construction.

2016-10-18 12:15 UTC, rafaelgmota commented
above modifications were done

2016-10-18 12:20 UTC, rafaelgmota commented on NoC/NOC.vhd
> +            clock_rx(i)(0)              <= clock_tx(i+NUM_Y)(1);
Modelsim 10.3 don't support it

2016-10-18 12:24 UTC, rafaelgmota commented
above possible modification were done

2016-10-18 12:26 UTC, jmferreiratech approved these changes

2016-10-18 12:27 UTC, merged