Get ride of std_logic_arith and std_logic_unsigned
LaNoC-UFC/Phoenix pull request #57
Opened 2016-11-01 18:57 UTC by rmilfont

Change the arithmetic library for numeric_std.

Commit:Mod

TaskNumber:#54

2016-11-01 23:26 UTC, jmferreiratech requested changes
You forgot also uses of std_logic_unsigned at inputModule and outputModule.

2016-11-01 23:26 UTC, jmarcelof commented on topNoC.vhd
>  use STD.textio.all;
Could you remote the std_logic_unsigned below?

2016-11-03 12:30 UTC, rmilfont commented on topNoC.vhd
>  use STD.textio.all;
Done.

2016-11-03 17:51 UTC, rafaelgmota approved these changes

2016-11-03 18:12 UTC, jmferreiratech approved these changes

2016-11-04 18:06 UTC, merged